# Generated by Django 4.1.7 on 2023-03-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
